# Generated by Django 5.1.3 on 2024-11-26 04:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_article_description_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
