# Generated by Django 5.1.3 on 2024-11-26 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_edition_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=30)),
                ('jog_title', models.CharField(max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_requests', to='app.article')),
            ],
        ),
    ]
