# Generated by Django 5.1.3 on 2024-11-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_pdfrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='editors_desk_speech',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
