# Generated by Django 5.1.3 on 2024-11-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_edition_editors_desk_speech'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfrequest',
            old_name='jog_title',
            new_name='job_title',
        ),
    ]
