# Generated by Django 5.1.3 on 2024-11-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_editionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='industry',
            field=models.CharField(blank=True, choices=[('FIN', 'Finance'), ('DATA', 'Data Analysis'), ('EDU', 'Education'), ('ENGR', 'Engineering'), ('SME', 'SME Development'), ('TM', 'Tourism'), ('CUST', 'Customer Care/experience Management')], max_length=10, null=True),
        ),
    ]
