# Generated by Django 5.1.3 on 2024-11-28 02:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_article_image_alter_article_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='editors_desk_speech',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
