# Generated by Django 5.1.3 on 2024-12-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_contributor_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='industry',
            field=models.CharField(blank=True, choices=[('FIN', 'Finance'), ('DATA', 'Data Analytics'), ('CUB', 'Construction Business'), ('ENGR', 'Engineering'), ('SME', 'SME Development'), ('TM', 'Tourism'), ('CUST', 'Customer Care/Experience Management')], max_length=10, null=True),
        ),
    ]
